/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/park_map.glb -t
*/

import React from "react";
import { OrthographicCamera } from "@react-three/drei";

export function CameraAndLight(props: JSX.IntrinsicElements["group"]) {
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        position={[30.37, 31.24, 30.16]}
        rotation={[-0.79, 0.62, 0.52]}
        zoom={50}
      />

      <pointLight
        intensity={5}
        decay={2}
        color="#ff6728"
        position={[-3.77, 2.82, -1.77]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <pointLight
        intensity={5}
        decay={2}
        color="#ff6728"
        position={[3.14, 2.92, -3.19]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <directionalLight
        // ref={directionalLightRef1}
        position={[0, 10, -1]}
        intensity={0.1}
        color="#53288f"
        castShadow
      />
      <directionalLight
        // ref={directionalLightRef2}
        position={[-7, 3, 10]}
        intensity={0.4}
        color="#6a00ff"
      />
    </group>
  );
}

export default CameraAndLight;
