/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f01.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f01_1: THREE.Mesh
    f01_2: THREE.Mesh
    f01_3: THREE.Mesh
  }
  materials: {
    stem: THREE.MeshStandardMaterial
    crokus: THREE.MeshStandardMaterial
    bammoo: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f01.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[2.85, 0.25, -72.83]} scale={0.17}>
        <mesh geometry={nodes.f01_1.geometry} material={materials.stem} />
        <mesh geometry={nodes.f01_2.geometry} material={materials.crokus} />
        <mesh geometry={nodes.f01_3.geometry} material={materials.bammoo} />
      </group>
    </group>
  )
}

useGLTF.preload('/f01.glb')
