/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f02.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f02_1: THREE.Mesh
    f02_2: THREE.Mesh
  }
  materials: {
    bell_2: THREE.MeshStandardMaterial
    stem: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f02.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[2.85, 0.26, -73.63]} rotation={[-1.1, 0.99, -2.47]} scale={0.05}>
        <mesh geometry={nodes.f02_1.geometry} material={materials.bell_2} />
        <mesh geometry={nodes.f02_2.geometry} material={materials.stem} />
      </group>
    </group>
  )
}

useGLTF.preload('/f02.glb')
