/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f03.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f03_1: THREE.Mesh
    f03_2: THREE.Mesh
  }
  materials: {
    ['Material.023']: THREE.MeshStandardMaterial
    stem: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f03.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[2.84, 0.26, -74.25]} rotation={[0.04, 0.46, -0.11]} scale={0.17}>
        <mesh geometry={nodes.f03_1.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.f03_2.geometry} material={materials.stem} />
      </group>
    </group>
  )
}

useGLTF.preload('/f03.glb')
