/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f04.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PositionType } from "../../models/garden/gardenType";
import { useLocation } from "react-router-dom";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    f04_1: THREE.Mesh;
    f04_2: THREE.Mesh;
    f04_3: THREE.Mesh;
    f04_4: THREE.Mesh;
    f04_5: THREE.Mesh;
  };
  materials: {
    ["Material.041"]: THREE.MeshStandardMaterial;
    ["Material.036"]: THREE.MeshStandardMaterial;
    ["Material.037"]: THREE.MeshStandardMaterial;
    ["Material.038"]: THREE.MeshStandardMaterial;
    ["Material.040"]: THREE.MeshStandardMaterial;
  };
};

export function F04(props: JSX.IntrinsicElements["group"] & PositionType) {
  const { x, y, z } = props.flowerPosition;
  const location = useLocation();
  const modelRef = useRef<any>();
  useFrame(() => {
    if (!location.pathname.includes("garden")) {
      const worldYAxis = new THREE.Vector3(0, 1, 0);
      modelRef.current!.rotateOnWorldAxis(worldYAxis, 0.01);
    }
  });

  const { nodes, materials } = useGLTF("/models/flowers/f04.glb") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group
        position={[x, y, z]}
        rotation={[2.76, -1.15, -2.79]}
        scale={0.17}
        ref={location.pathname.includes("garden") ? undefined : modelRef}
      >
        <mesh
          geometry={nodes.f04_1.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          geometry={nodes.f04_2.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          geometry={nodes.f04_3.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          geometry={nodes.f04_4.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          geometry={nodes.f04_5.geometry}
          material={materials["Material.040"]}
        />
      </group>
    </group>
  );
}

export default F04;
