/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f06.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f06_1: THREE.Mesh
    f06_2: THREE.Mesh
    f06_3: THREE.Mesh
  }
  materials: {
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    stem: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f06.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[2.85, 0.26, -75.73]} rotation={[0.27, -0.34, -0.47]} scale={0.17}>
        <mesh geometry={nodes.f06_1.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.f06_2.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.f06_3.geometry} material={materials.stem} />
      </group>
    </group>
  )
}

useGLTF.preload('/f06.glb')
