/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f06.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PositionType } from "../../models/garden/gardenType";

type GLTFResult = GLTF & {
  nodes: {
    f06_1: THREE.Mesh;
    f06_2: THREE.Mesh;
    f06_3: THREE.Mesh;
  };
  materials: {
    ["Material.029"]: THREE.MeshStandardMaterial;
    ["Material.030"]: THREE.MeshStandardMaterial;
    stem: THREE.MeshStandardMaterial;
  };
};

export function F06(props: JSX.IntrinsicElements["group"] & PositionType) {
  const { x, y, z } = props.flowerPosition;

  const { nodes, materials } = useGLTF("/models/flowers/f06.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[x, y, z]} rotation={[0.27, -0.34, -0.47]} scale={0.17}>
        <mesh
          geometry={nodes.f06_1.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          geometry={nodes.f06_2.geometry}
          material={materials["Material.030"]}
        />
        <mesh geometry={nodes.f06_3.geometry} material={materials.stem} />
      </group>
    </group>
  );
}

export default F06;
