/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f07.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f07_1: THREE.Mesh
    f07_2: THREE.Mesh
    f07_3: THREE.Mesh
    f07_4: THREE.Mesh
  }
  materials: {
    bammoo2: THREE.MeshStandardMaterial
    bammoo3: THREE.MeshStandardMaterial
    bammoo: THREE.MeshStandardMaterial
    stem: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f07.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[2.9, 0.28, -76.24]} rotation={[2.54, 1.46, -2.25]} scale={[0.03, 0.01, 0.03]}>
        <mesh geometry={nodes.f07_1.geometry} material={materials.bammoo2} />
        <mesh geometry={nodes.f07_2.geometry} material={materials.bammoo3} />
        <mesh geometry={nodes.f07_3.geometry} material={materials.bammoo} />
        <mesh geometry={nodes.f07_4.geometry} material={materials.stem} />
      </group>
    </group>
  )
}

useGLTF.preload('/f07.glb')
