/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f08.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PositionType } from "../../models/garden/gardenType";

type GLTFResult = GLTF & {
  nodes: {
    f08_1: THREE.Mesh;
    f08_2: THREE.Mesh;
    f08_3: THREE.Mesh;
  };
  materials: {
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    stem: THREE.MeshStandardMaterial;
  };
};

export function F08(props: JSX.IntrinsicElements["group"] & PositionType) {
  const { x, y, z } = props.flowerPosition;

  const { nodes, materials } = useGLTF("/models/flowers/f08.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[x, y, z]} scale={0.17}>
        <mesh
          geometry={nodes.f08_1.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={nodes.f08_2.geometry}
          material={materials["Material.014"]}
        />
        <mesh geometry={nodes.f08_3.geometry} material={materials.stem} />
      </group>
    </group>
  );
}

export default F08;
