/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f09.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f09_1: THREE.Mesh
    f09_2: THREE.Mesh
    f09_3: THREE.Mesh
    f09_4: THREE.Mesh
  }
  materials: {
    bammoo: THREE.MeshStandardMaterial
    stem: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f09.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.97, 0.26, -72.67]} scale={0.17}>
        <mesh geometry={nodes.f09_1.geometry} material={materials.bammoo} />
        <mesh geometry={nodes.f09_2.geometry} material={materials.stem} />
        <mesh geometry={nodes.f09_3.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.f09_4.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/f09.glb')
