/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f10.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PositionType } from "../../models/garden/gardenType";

type GLTFResult = GLTF & {
  nodes: {
    f10_1: THREE.Mesh;
    f10_2: THREE.Mesh;
  };
  materials: {
    bell: THREE.MeshStandardMaterial;
    stem: THREE.MeshStandardMaterial;
  };
};

export function F10(props: JSX.IntrinsicElements["group"] & PositionType) {
  const { x, y, z } = props.flowerPosition;

  const { nodes, materials } = useGLTF("/models/flowers/f10.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[x, y, z]} rotation={[-1.4, -0.57, -3.1]} scale={0.17}>
        <mesh geometry={nodes.f10_1.geometry} material={materials.bell} />
        <mesh geometry={nodes.f10_2.geometry} material={materials.stem} />
      </group>
    </group>
  );
}

export default F10;
