/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f11.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f11_1: THREE.Mesh
    f11_2: THREE.Mesh
    f11_3: THREE.Mesh
    f11_4: THREE.Mesh
  }
  materials: {
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    stem: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f11.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.9, 0.27, -73.81]} rotation={[-0.97, -0.39, -1.42]} scale={0.17}>
        <mesh geometry={nodes.f11_1.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.f11_2.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.f11_3.geometry} material={materials.stem} />
        <mesh geometry={nodes.f11_4.geometry} material={materials['Material.019']} />
      </group>
    </group>
  )
}

useGLTF.preload('/f11.glb')
