/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f13.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f13_1: THREE.Mesh
    f13_2: THREE.Mesh
    f13_3: THREE.Mesh
    f13_4: THREE.Mesh
  }
  materials: {
    stem: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f13.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.93, 0.27, -75.11]} scale={0.17}>
        <mesh geometry={nodes.f13_1.geometry} material={materials.stem} />
        <mesh geometry={nodes.f13_2.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.f13_3.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.f13_4.geometry} material={materials['Material.028']} />
      </group>
    </group>
  )
}

useGLTF.preload('/f13.glb')
