/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f17.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PositionType } from "../../models/garden/gardenType";
import { useLocation } from "react-router-dom";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    f17_1: THREE.Mesh;
    f17_2: THREE.Mesh;
    f17_3: THREE.Mesh;
    f17_4: THREE.Mesh;
  };
  materials: {
    stem: THREE.MeshStandardMaterial;
    maebaltob2: THREE.MeshStandardMaterial;
    maebaltob: THREE.MeshStandardMaterial;
    bammoo3: THREE.MeshStandardMaterial;
  };
};

export function F17(props: JSX.IntrinsicElements["group"] & PositionType) {
  const { x, y, z } = props.flowerPosition;
  const location = useLocation();
  const modelRef = useRef<any>();
  useFrame(() => {
    if (!location.pathname.includes("garden")) {
      const worldYAxis = new THREE.Vector3(0, 1, 0);
      modelRef.current!.rotateOnWorldAxis(worldYAxis, 0.01);
    }
  });

  const { nodes, materials } = useGLTF("/models/flowers/f17.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[x, y, z]}
        rotation={[0, -1.3, -Math.PI / 2]}
        scale={[0.13, 0.08, 0.1]}
        ref={location.pathname.includes("garden") ? undefined : modelRef}
      >
        <mesh geometry={nodes.f17_1.geometry} material={materials.stem} />
        <mesh geometry={nodes.f17_2.geometry} material={materials.maebaltob2} />
        <mesh geometry={nodes.f17_3.geometry} material={materials.maebaltob} />
        <mesh geometry={nodes.f17_4.geometry} material={materials.bammoo3} />
      </group>
    </group>
  );
}

export default F17;
