/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f18.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PositionType } from "../../models/garden/gardenType";

type GLTFResult = GLTF & {
  nodes: {
    f18_1: THREE.Mesh;
    f18_2: THREE.Mesh;
    f18_3: THREE.Mesh;
  };
  materials: {
    stem: THREE.MeshStandardMaterial;
    anemone: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
  };
};

export function F18(props: JSX.IntrinsicElements["group"] & PositionType) {
  const { x, y, z } = props.flowerPosition;

  const { nodes, materials } = useGLTF("/models/flowers/f18.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[x, y, z]} rotation={[1.95, -1.22, -2.12]} scale={0.17}>
        <mesh geometry={nodes.f18_1.geometry} material={materials.stem} />
        <mesh geometry={nodes.f18_2.geometry} material={materials.anemone} />
        <mesh geometry={nodes.f18_3.geometry} material={materials.Material} />
      </group>
    </group>
  );
}

export default F18;
