/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f18.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f18_1: THREE.Mesh
    f18_2: THREE.Mesh
    f18_3: THREE.Mesh
  }
  materials: {
    stem: THREE.MeshStandardMaterial
    anemone: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f18.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[1.9, 0.26, -75.06]} rotation={[1.95, -1.22, -2.12]} scale={0.17}>
        <mesh geometry={nodes.f18_1.geometry} material={materials.stem} />
        <mesh geometry={nodes.f18_2.geometry} material={materials.anemone} />
        <mesh geometry={nodes.f18_3.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/f18.glb')
