/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f19.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PositionType } from "../../models/garden/gardenType";
import { useLocation } from "react-router-dom";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    f19_1: THREE.Mesh;
    f19_2: THREE.Mesh;
    f19_3: THREE.Mesh;
    f19_4: THREE.Mesh;
  };
  materials: {
    ["Material.042"]: THREE.MeshStandardMaterial;
    ["Material.043"]: THREE.MeshStandardMaterial;
    ["Material.044"]: THREE.MeshStandardMaterial;
    ["Material.045"]: THREE.MeshStandardMaterial;
  };
};

export function F19(props: JSX.IntrinsicElements["group"] & PositionType) {
  const { x, y, z } = props.flowerPosition;
  const location = useLocation();
  const modelRef = useRef<any>();
  useFrame(() => {
    if (!location.pathname.includes("garden")) {
      const worldYAxis = new THREE.Vector3(0, 1, 0);
      modelRef.current!.rotateOnWorldAxis(worldYAxis, 0.01);
    }
  });

  const { nodes, materials } = useGLTF("/models/flowers/f19.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[x, y, z]}
        scale={0.2}
        ref={location.pathname.includes("garden") ? undefined : modelRef}
      >
        <mesh
          geometry={nodes.f19_1.geometry}
          material={materials["Material.042"]}
        />
        <mesh
          geometry={nodes.f19_2.geometry}
          material={materials["Material.043"]}
        />
        <mesh
          geometry={nodes.f19_3.geometry}
          material={materials["Material.044"]}
        />
        <mesh
          geometry={nodes.f19_4.geometry}
          material={materials["Material.045"]}
        />
      </group>
    </group>
  );
}

export default F19;
