/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f19.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f19_1: THREE.Mesh
    f19_2: THREE.Mesh
    f19_3: THREE.Mesh
    f19_4: THREE.Mesh
  }
  materials: {
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    ['Material.044']: THREE.MeshStandardMaterial
    ['Material.045']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f19.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[1.91, 0.28, -75.65]} scale={0.17}>
        <mesh geometry={nodes.f19_1.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.f19_2.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.f19_3.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.f19_4.geometry} material={materials['Material.045']} />
      </group>
    </group>
  )
}

useGLTF.preload('/f19.glb')
