/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f20.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PositionType } from "../../models/garden/gardenType";
import { useLocation } from "react-router-dom";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    f20_1: THREE.Mesh;
    f20_2: THREE.Mesh;
    f20_3: THREE.Mesh;
    f20_4: THREE.Mesh;
  };
  materials: {
    stem: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    f20: THREE.MeshStandardMaterial;
    ["sineraria.001"]: THREE.MeshStandardMaterial;
  };
};

export function F20(props: JSX.IntrinsicElements["group"] & PositionType) {
  const { x, y, z } = props.flowerPosition;
  const location = useLocation();
  const modelRef = useRef<any>();
  useFrame(() => {
    if (!location.pathname.includes("garden")) {
      const worldYAxis = new THREE.Vector3(0, 1, 0);
      modelRef.current!.rotateOnWorldAxis(worldYAxis, 0.01);
    }
  });

  const { nodes, materials } = useGLTF("/models/flowers/f20.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[x, y, z]}
        rotation={[0, -1.3, -Math.PI / 2]}
        scale={0.17}
        ref={location.pathname.includes("garden") ? undefined : modelRef}
      >
        <mesh geometry={nodes.f20_1.geometry} material={materials.stem} />
        <mesh
          geometry={nodes.f20_2.geometry}
          material={materials["Material.005"]}
        />
        <mesh geometry={nodes.f20_3.geometry} material={materials.f20} />
        <mesh
          geometry={nodes.f20_4.geometry}
          material={materials["sineraria.001"]}
        />
      </group>
    </group>
  );
}

export default F20;
