/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f20.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f20_1: THREE.Mesh
    f20_2: THREE.Mesh
    f20_3: THREE.Mesh
    f20_4: THREE.Mesh
  }
  materials: {
    stem: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    f20: THREE.MeshStandardMaterial
    ['sineraria.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f20.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[1.94, 0.26, -76.26]} rotation={[0, -1.3, -Math.PI / 2]} scale={0.17}>
        <mesh geometry={nodes.f20_1.geometry} material={materials.stem} />
        <mesh geometry={nodes.f20_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.f20_3.geometry} material={materials.f20} />
        <mesh geometry={nodes.f20_4.geometry} material={materials['sineraria.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/f20.glb')
