/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f22.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    f22_1: THREE.Mesh
    f22_2: THREE.Mesh
    f22_3: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    stem: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/f22.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.25, 0.26, -72.66]} rotation={[-3.07, -0.6, -2.78]} scale={0.17}>
        <mesh geometry={nodes.f22_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.f22_2.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.f22_3.geometry} material={materials.stem} />
      </group>
    </group>
  )
}

useGLTF.preload('/f22.glb')
