/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/flowers/f23.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PositionType } from "../../models/garden/gardenType";

type GLTFResult = GLTF & {
  nodes: {
    f23_1: THREE.Mesh;
    f23_2: THREE.Mesh;
    f23_3: THREE.Mesh;
  };
  materials: {
    ["Material.032"]: THREE.MeshStandardMaterial;
    ["Material.033"]: THREE.MeshStandardMaterial;
    stem: THREE.MeshStandardMaterial;
  };
};

export function F23(props: JSX.IntrinsicElements["group"] & PositionType) {
  const { x, y, z } = props.flowerPosition;

  const { nodes, materials } = useGLTF("/models/flowers/f23.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[x, y, z]} rotation={[0, 0, -0.19]} scale={0.17}>
        <mesh
          geometry={nodes.f23_1.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          geometry={nodes.f23_2.geometry}
          material={materials["Material.033"]}
        />
        <mesh geometry={nodes.f23_3.geometry} material={materials.stem} />
      </group>
    </group>
  );
}

export default F23;
