/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/camp_map.glb -t
*/

import React from "react";

import { OrthographicCamera } from "@react-three/drei";

export function CameraAndLight(props: JSX.IntrinsicElements["group"]) {
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        // fov={42.18}
        position={[9.86, 8.71, 9.86]}
        rotation={[-0.71, 0.65, 0.48]}
        zoom={50}
      />
      <pointLight
        intensity={1}
        decay={2}
        color="#6e8bff"
        position={[-3.77, 2.82, -1.77]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <pointLight
        intensity={1}
        decay={2}
        color="#ffc6f8"
        position={[3.14, 2.92, -3.19]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <directionalLight
        position={[0, 10, -1]}
        intensity={2}
        color="#ffbf8d"
        castShadow
      />
      <directionalLight position={[-7, 3, 10]} intensity={2} color="#1a0070" />
    </group>
  );
}

export default CameraAndLight;
