/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/base_map_new.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Water: THREE.Mesh;
    Base_Ground: THREE.Mesh;
    Tree2: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube009: THREE.Mesh;
    Bench: THREE.Mesh;
    Vert001: THREE.Mesh;
    Vert002: THREE.Mesh;
    Circle001: THREE.Mesh;
    Circle001_1: THREE.Mesh;
    Tree1: THREE.Mesh;
    Cube033: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube036: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube038: THREE.Mesh;
    Cube039: THREE.Mesh;
    Cube040: THREE.Mesh;
    Cube041: THREE.Mesh;
    Cube042: THREE.Mesh;
    Cube043: THREE.Mesh;
    Circle001_2: THREE.Mesh;
    Circle001_3: THREE.Mesh;
    Rock004: THREE.Mesh;
    Grass005: THREE.Mesh;
    Grass006: THREE.Mesh;
    Bg: THREE.Mesh;
    Base_Grass: THREE.Mesh;
    Rock006: THREE.Mesh;
    Grass012: THREE.Mesh;
    Grass014: THREE.Mesh;
    Grass015: THREE.Mesh;
  };
  materials: {
    Water: THREE.MeshStandardMaterial;
    Ground: THREE.MeshStandardMaterial;
    Tree: THREE.MeshStandardMaterial;
    leaf2: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    Light: THREE.MeshStandardMaterial;
    Rock: THREE.MeshStandardMaterial;
    ["Grass.001"]: THREE.MeshStandardMaterial;
    Bg: THREE.MeshStandardMaterial;
    Grass: THREE.MeshStandardMaterial;
  };
};

type GLTFResult1 = GLTF & {
  nodes: {
    Cylinder073: THREE.Mesh;
    Cylinder073_1: THREE.Mesh;
    Cylinder073_2: THREE.Mesh;
    Cylinder073_3: THREE.Mesh;
  };
  materials: {
    ["Material.020"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    stem: THREE.MeshStandardMaterial;
    ["Material.019"]: THREE.MeshStandardMaterial;
  };
};

export function CameraAndLight(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/base_map_new.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <OrthographicCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        position={[30.37, 31.24, 30.16]}
        rotation={[-0.79, 0.62, 0.52]}
        zoom={50}
      />

      <pointLight
        intensity={5}
        decay={2}
        color="#ff6728"
        position={[-3.77, 2.82, -1.77]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <pointLight
        intensity={5}
        decay={2}
        color="#ff6728"
        position={[3.14, 2.92, -3.19]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <directionalLight
        // ref={directionalLightRef1}
        position={[0, 10, -1]}
        intensity={0.1}
        color="#53288f"
        castShadow
      />
      <directionalLight
        // ref={directionalLightRef2}
        position={[-7, 3, 10]}
        intensity={0.4}
        color="#6a00ff"
      />
    </group>
  );
}

export default CameraAndLight;
